name: 'jaffle_shop'
version: '1.0.0'
config-version: 2
profile: 'databricks'  # <--- AJOUTE CETTE LIGNE
# C'est ici qu'on définit où dbt cherche les fichiers
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  jaffle_shop:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table