name: 'jaffle_shop'
version: '1.0.0'
config-version: 2
profile: 'databricks'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  jaffle_shop:
    # Cette section s'applique aux fichiers dans models/staging/
    staging:
      +schema: staging      # dbt cherchera à créer [votre_schema]_staging
      +materialized: view
    # Cette section s'applique aux fichiers dans models/marts/
    marts:
      +schema: marts        # dbt cherchera à créer [votre_schema]_marts
      +materialized: table