version: 2

sources:
  - name: jaffle_shop_raw
    catalog: marketing_db     # Ton catalogue
    schema: jaffle_shop       # Ton schéma actuel avec les tables
    tables:
      - name: customers
      - name: orders
      - name: payments